spring:
  session:
    jdbc:
      initialize-schema: never
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 250
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret-key: "bGVhc3RuZXJ2b3VzYWdvbGlwc25pZ2h0bWVjb25zdGFudGx5c2Nob29sb3JzdGFpcnM="
      access-token-expiration: 1800000
      refresh-token-expiration: 604800000
debug: false
